#tomcat port
server:
  port: 9000
  #jsp
spring:
 # mvc:
 #   view:
  #    prefix: /WEB-INF/ipgo/
  #    suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee?serverTimezone=Asia/Seoul
    username: phc
    password: 1234
#mybatis
mybatis:
  type-aliases-package: boot.data.*
  mapper-locations: 
  - /mapper/**/*.xml    